version: "3.9"

services:
  db:
    image: mysql:8
    container_name: sb_mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpw
      TZ: ${TZ}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpw"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build:
      context: .
      args:
        TZ: ${TZ}
    container_name: sb_web
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # 엔트리포인트 스크립트 사용 중이면 유지
    # entrypoint는 Dockerfile에서 ENTRYPOINT ["sh", "docker/entrypoint.sh"] 로 지정되어 있음

volumes:
  db_data: {}   