version: "3.9"

services:
  db:
    image: mysql:8
    container_name: sb_mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpw
      TZ: ${TZ}
    ports:
<<<<<<< HEAD
      - "13306:3306"
=======
      - "3306:3306"
>>>>>>> seil2
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpw"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build:
      context: .
      args:
        TZ: ${TZ}
    container_name: sb_web
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
<<<<<<< HEAD
      - "8080:8000"
    # 엔트리포인트 스크립트 사용 중이면 유지
    # entrypoint는 Dockerfile에서 ENTRYPOINT ["sh", "docker/entrypoint.sh"] 로 지정되어 있음

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: sb_prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.2.3
    container_name: sb_grafana
    depends_on:
      prometheus:
        condition: service_started
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  db_data: {}
  prometheus_data: {}
  grafana_data: {}
=======
      - "8000:8000"
    # 엔트리포인트 스크립트 사용 중이면 유지
    # entrypoint는 Dockerfile에서 ENTRYPOINT ["sh", "docker/entrypoint.sh"] 로 지정되어 있음

volumes:
  db_data: {}   
>>>>>>> seil2
