# Generated by Django 5.2.6 on 2025-09-17 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cert_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='certificates.certificatelevel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
