# Generated by Django 5.2.6 on 2025-09-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rating',
            table=None,
        ),
    ]
