# Generated by Django 5.2.6 on 2025-09-23 08:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('authority', models.CharField(blank=True, max_length=255)),
                ('cert_type', models.CharField(blank=True, max_length=100)),
                ('homepage', models.URLField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('expected_duration', models.PositiveIntegerField(blank=True, help_text='예상 학습기간(주)', null=True)),
                ('expected_duration_major', models.PositiveIntegerField(blank=True, help_text='전공자 기준(주)', null=True)),
            ],
            options={
                'db_table': 'certificate',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificatePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=50)),
                ('phase_type', models.CharField(choices=[('필기', '필기'), ('실기', '실기')], max_length=10)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='certificates.certificate')),
            ],
            options={
                'db_table': 'certificate_phase',
            },
        ),
        migrations.CreateModel(
            name='CertificateStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('필기', '필기'), ('실기', '실기')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('registered', models.PositiveIntegerField(blank=True, null=True)),
                ('applicants', models.PositiveIntegerField(blank=True, null=True)),
                ('passers', models.PositiveIntegerField(blank=True, null=True)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='certificates.certificate')),
            ],
            options={
                'db_table': 'certificate_statistics',
                'ordering': ['-year', 'exam_type', 'session'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.tag')),
            ],
            options={
                'db_table': 'certificate_tag',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='certificates', through='certificates.CertificateTag', to='certificates.tag'),
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='certificates.tag')),
            ],
            options={
                'db_table': 'user_tag',
            },
        ),
    ]
