# Generated by Django 5.2.6 on 2025-09-29 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('overview', models.TextField(blank=True)),
                ('job_roles', models.TextField(blank=True)),
                ('exam_method', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('expected_duration', models.IntegerField(blank=True, null=True)),
                ('expected_duration_major', models.IntegerField(blank=True, null=True)),
                ('authority', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('homepage', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'certificate',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificatePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=255)),
                ('phase_type', models.CharField(max_length=255)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='certificates.certificate')),
            ],
            options={
                'db_table': 'certificate_phase',
                'unique_together': {('certificate', 'phase_name', 'phase_type')},
            },
        ),
        migrations.CreateModel(
            name='CertificateStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('session', models.IntegerField(blank=True, null=True)),
                ('registered', models.IntegerField(blank=True, null=True)),
                ('applicants', models.IntegerField(blank=True, null=True)),
                ('passers', models.IntegerField(blank=True, null=True)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='certificates.certificate')),
            ],
            options={
                'db_table': 'certificate_statistics',
                'ordering': ['-year', 'exam_type', 'session'],
                'unique_together': {('certificate', 'exam_type', 'year', 'session')},
            },
        ),
        migrations.CreateModel(
            name='CertificateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.tag')),
            ],
            options={
                'db_table': 'certificate_tag',
                'unique_together': {('certificate', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_certificate',
                'unique_together': {('user', 'certificate')},
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='certificates.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tag',
                'ordering': ['id'],
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
