# Generated by Django 5.2.6 on 2025-09-17 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('authority', models.CharField(blank=True, max_length=255)),
                ('cert_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=255)),
                ('level_description', models.TextField(blank=True)),
                ('homepage', models.URLField(blank=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='certificates.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('applicants', models.IntegerField(blank=True, null=True)),
                ('passers', models.IntegerField(blank=True, null=True)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cert_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='certificates.certificatelevel')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.tag')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='tags',
            field=models.ManyToManyField(through='certificates.CertificateTag', to='certificates.tag'),
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate')),
            ],
        ),
    ]
