# Generated by Django 5.2.6 on 2025-09-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatephase',
            options={'ordering': ['certificate_id', 'phase_name']},
        ),
        migrations.AlterModelOptions(
            name='certificatestatistics',
            options={'ordering': ['certificate_id', 'year', 'session']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='tags',
            field=models.ManyToManyField(related_name='certificates', through='certificates.CertificateTag', to='certificates.tag'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='exam_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='homepage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='certificatephase',
            name='phase_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='certificatestatistics',
            name='exam_type',
            field=models.CharField(default='필기', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificatestatistics',
            name='pass_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificatestatistics',
            name='year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='certificate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='certificatephase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='certificatestatistics',
            table=None,
        ),
        migrations.AlterModelTable(
            name='certificatetag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
        migrations.DeleteModel(
            name='UserCertificate',
        ),
    ]
