# Generated by Django 5.2.6 on 2025-09-23 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='certificatephase',
            index=models.Index(fields=['certificate', 'phase_type'], name='certificate_certifi_9f156e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificatephase',
            unique_together={('certificate', 'phase_name', 'phase_type')},
        ),
        migrations.AddIndex(
            model_name='certificatestatistics',
            index=models.Index(fields=['certificate', 'exam_type', 'year'], name='certificate_certifi_5778b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificatestatistics',
            unique_together={('certificate', 'exam_type', 'year', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='certificatetag',
            unique_together={('certificate', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='usertag',
            unique_together={('user', 'tag')},
        ),
    ]
