# Generated by Django 5.2.6 on 2025-09-30 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificatephase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatephase',
            name='phase_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='certificatestatistics',
            name='exam_type',
            field=models.CharField(default='필기', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificatestatistics',
            name='pass_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_holders', to='certificates.certificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_certificate',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'certificate')},
            },
        ),
    ]
