# Generated by Django 5.2.6 on 2025-10-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificatephase_phase_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='homepage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
