# Generated by Django 5.2.6 on 2025-10-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificate_homepage_alter_certificate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='exam_method',
            field=models.TextField(blank=True),
        ),
    ]
