# Generated by Django 5.2.6 on 2025-10-17 05:33

import certificates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_certificate_exam_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertificate',
            name='evidence',
            field=models.FileField(blank=True, upload_to=certificates.models.user_certificate_upload_to),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='status',
            field=models.CharField(choices=[('pending', '심사중'), ('approved', '등록완료'), ('rejected', '반려')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
