# Generated by Django 5.2.6 on 2025-10-21 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('tag_request', '자격증 추가 요청'), ('info_update', '정보 수정'), ('stats_request', '통계 요청'), ('bug_report', '시스템 오류 신고'), ('general_help', '기타 문의')], max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('conversation', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '대기'), ('in_progress', '처리 중'), ('resolved', '처리 완료')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
