# Generated by Django 5.2.6 on 2025-10-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_supportinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportinquiry',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('in_progress', '처리 중'), ('rejected', '반려'), ('resolved', '처리 완료')], default='pending', max_length=20),
        ),
    ]
